import jsPDF from 'jspdf';

export interface PackSlipItem {
  name: string;
  quantity: number;
}

export interface PackSlipOrder {
  orderNumber: string;
  createdAt: string;
  customerName: string;
  phone?: string | null;
  shippingAddress?: string | null;
  storeName?: string | null;
  channel?: string | null;
  paymentType?: string | null;
  total: number;
  notes?: string | null;
}

const fmt = (value: number) => new Intl.NumberFormat('en-IN').format(Math.round(value));

/** A6-ish compact pack slip meant to be taped onto the parcel. */
export function generatePackSlip(order: PackSlipOrder, items: PackSlipItem[]) {
  const doc = new jsPDF({ unit: 'mm', format: 'a5' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 12;
  let y = 16;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text('PACK SLIP', margin, y);
  doc.setFontSize(10);
  doc.text(order.orderNumber, pageWidth - margin, y, { align: 'right' });
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(110);
  doc.text(
    `${order.storeName || 'SeeCen'} · ${new Date(order.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}${order.channel ? ` · ${order.channel.replace(/_/g, ' ')}` : ''}`,
    margin,
    y
  );
  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  // Ship-to block
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('SHIP TO', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(order.customerName, margin, y);
  y += 5;
  if (order.phone) {
    doc.text(order.phone, margin, y);
    y += 5;
  }
  if (order.shippingAddress) {
    const lines = doc.splitTextToSize(order.shippingAddress, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 5;
  }
  y += 3;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  // Items with checkboxes for the packer
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('ITEMS', margin, y);
  doc.text('QTY', pageWidth - margin, y, { align: 'right' });
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  for (const item of items) {
    doc.setDrawColor(120);
    doc.rect(margin, y - 3.4, 3.6, 3.6); // tick box
    const nameLines = doc.splitTextToSize(item.name, pageWidth - margin * 2 - 20);
    doc.text(nameLines, margin + 6, y);
    doc.text(`x${item.quantity}`, pageWidth - margin, y, { align: 'right' });
    y += nameLines.length * 5 + 2;
    if (y > 185) {
      doc.addPage();
      y = 16;
    }
  }
  y += 2;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 7;

  // Payment strip — the packer needs to know if cash must be collected
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  if (order.paymentType === 'cod') {
    doc.setTextColor(190, 30, 30);
    doc.text(`COD — COLLECT Rs. ${fmt(order.total)}`, margin, y);
  } else {
    doc.setTextColor(20, 130, 60);
    doc.text('PREPAID — do not collect payment', margin, y);
  }
  doc.setTextColor(0);
  y += 8;

  if (order.notes) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('NOTES', margin, y);
    y += 5;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    const noteLines = doc.splitTextToSize(order.notes, pageWidth - margin * 2);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 4.5;
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(150);
  doc.text('Generated by SeeCen', margin, 200);

  doc.save(`packslip-${order.orderNumber}.pdf`);
}
